---
# Destroy VPC infrastructure playbook
- hosts: localhost
  remote_user: root
  become: true
  collections:
    - amazon.aws
  vars_files:
    - defaults/main.yml
  tasks:
    - name: Delete security groups
      amazon.aws.ec2_group:
        name: "{{ web_sg_name }}"
        vpc_id: "{{ vpc_id }}"
        region: "{{ aws_region }}"
        state: absent
        aws_access_key: "{{ aws_access_key }}"
        aws_secret_key: "{{ aws_secret_key }}"
      ignore_errors: yes

    - name: Delete database security group
      amazon.aws.ec2_group:
        name: "{{ db_sg_name }}"
        vpc_id: "{{ vpc_id }}"
        region: "{{ aws_region }}"
        state: absent
        aws_access_key: "{{ aws_access_key }}"
        aws_secret_key: "{{ aws_secret_key }}"
      ignore_errors: yes

    - name: Delete route tables
      amazon.aws.ec2_vpc_route_table:
        vpc_id: "{{ vpc_id }}"
        region: "{{ aws_region }}"
        state: absent
        aws_access_key: "{{ aws_access_key }}"
        aws_secret_key: "{{ aws_secret_key }}"
      ignore_errors: yes

    - name: Delete Internet Gateway
      amazon.aws.ec2_vpc_igw:
        vpc_id: "{{ vpc_id }}"
        region: "{{ aws_region }}"
        state: absent
        aws_access_key: "{{ aws_access_key }}"
        aws_secret_key: "{{ aws_secret_key }}"
      ignore_errors: yes

    - name: Delete subnets
      amazon.aws.ec2_vpc_subnet:
        vpc_id: "{{ vpc_id }}"
        region: "{{ aws_region }}"
        state: absent
        aws_access_key: "{{ aws_access_key }}"
        aws_secret_key: "{{ aws_secret_key }}"
      ignore_errors: yes

    - name: Delete VPC
      amazon.aws.ec2_vpc_net:
        vpc_id: "{{ vpc_id }}"
        region: "{{ aws_region }}"
        state: absent
        aws_access_key: "{{ aws_access_key }}"
        aws_secret_key: "{{ aws_secret_key }}"
      ignore_errors: yes

    - name: Debug completion
      debug:
        msg: "VPC infrastructure destroyed successfully"
