---
galaxy_info:
  author: your_name
  description: Ansible role for creating AWS VPC infrastructure
  company: your_company
  license: MIT
  min_ansible_version: 2.9
  platforms:
    - name: Ubuntu
      versions:
        - focal
        - jammy
  galaxy_tags:
    - aws
    - vpc
    - networking
    - infrastructure

dependencies: []
