---
- hosts: localhost
  gather_facts: true
  vars_files:
    - db_vault.yml
  tasks:
    - name: Create variables
      set_fact:
        db_file_name: "{{ db_name }}_{{ ansible_date_time.date | replace('-','') }}.sql"
    
    - name: Confirm hostname
      debug:
        msg: Logged into the server.

    - name: Download Database to server
      shell: |
        mysqldump -h {{ db_host }} --set-gtid-purged=OFF -u {{ db_user }} -p{{ db_pass }} {{ db_name }} {{ tb_name }} > "{{ db_file_name }}"
      no_log: false

    - name: Wait until the database backup completed on server
      wait_for:
        path: "{{ db_file_name }}"
        state: present
        msg: "Timeout to find file {{ db_file_name }}"

    - name: Downloading backup to local computer
      ansible.builtin.fetch:
        src: "{{ db_file_name }}"
        dest: "{{ db_file_name }}"
        flat: yes

    - name: Download completed
      debug:
        msg: Database have been downloaded successfully.

    - name: Rename the existing table
      shell: |
        mysql -h {{ db_host }} -P {{ db_port }} -u jakir -p{{ db_pass }} -e "RENAME TABLE {{ tb_name }} TO {{ new_tb }};" {{ db_name }}
      no_log: false

    - name: Restoring table in MySQL
      shell: |
        mysql -h {{ db_host }} -u {{ db_user }} -p{{ db_pass }} {{ db_name }} < "{{ db_file_name }}"
